modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/aaavein/patience/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/aaavein/patience" #optional
logoFile="icon.png" #optional
#credits="" #optional
authors="${mod_authors}" #optional
description='''${mod_description}''' #mandatory
modCategory="utility"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies."${mod_id}"]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="${neo_version_range}" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
